## 错误与异常

### try...catch

try...catch 语句作为 js 中的处理异常的一种标准方式. try 语句标记一块待尝试的语句, 如果该语句出现错误, 则通过 catch 语句进行捕获. 

```
try: {
    // 可能会导致错误的代码
} catch /捕捉块/ (error) {
    // 在错误发生时的处理
}
```

```
try {
    console.log(v) // 调用未定义变量
}
// 用于处理 try 语句中出现的错误信息
catch (error) {
    // error 表示 try 语句中出现的错误信息
    console.log('error')
}
// 终结块 catch 语句中无法处理 try 语句中的错误或异常时, 执行 finally 语句中的内容
finally {}
```

### 嵌套 try...catch 语句

可以嵌套一个或多个 try...catch 语句. 如果一个内部的 try...catch 语句没有捕捉块, 将会启动匹配外部的 try...catch 语句的捕捉块

```
try {
    console.log(0)
    } catch (error) {
        try {
            console.log(1)
        } catch (error) {
            console.log(2)
        }
    }
}
```

### 基本错误类型

执行代码期间可能会发生的错误有多中类型, 每种类型都有对应的错误类型. 当错误发生时, 就会抛出对应类型的错误对象. Error 是基本错误类型, 其他错误类型都是集成自该类型. Error 类型的错误很少见, 如果有也是浏览器抛出的. 这个基本错误类型的主要目的是提供给开发人员抛出自定义错误的.

### 预定义错误类型

js 的七种预定义的错误类型:

| 错误类型       | 说明                                                         |
| -------------- | ------------------------------------------------------------ |
| EvalError      | 表示错误的原因: 与eval()有关                                 |
| InternalError  | 表示js 引擎内部错误的异常                                    |
| RangeError     | 表示错误的原因: 数值变量或参数超出其有效范围                 |
| ReferenceError | 表示错误的原因: 无效引用                                     |
| SyntaxError    | 表示错误的原因: eval() 在解析代码的过程中发生的语法错误      |
| TypeError      | 表示错误的原因: 变量或参数不属于有效类型                     |
| URIError       | 表示错误的原因: 给 encodeURL() 或 decodeURL() 传递的参数无效 |